# Generated by Django 3.2.11 on 2022-01-29 05:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the book's language (e.g. English, French, Japanese, etc.)", max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('097fba68-d280-4582-85cf-33cf4513f42a'), help_text='Unique ID for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
