# Generated by Django 3.2.11 on 2022-01-29 05:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220129_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5330ae79-7b54-455a-a1f3-26e4a8301a0c'), help_text='Unique ID for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
