# Generated by Django 3.2.11 on 2022-01-29 05:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5985b687-6349-48f5-8526-fa07598b0b74'), help_text='Unique ID for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
