# Generated by Django 3.2.11 on 2022-01-29 07:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('31ed4cba-8944-48eb-848e-37b9b873a8a0'), help_text='Unique ID for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
