# Generated by Django 3.2.11 on 2022-01-29 07:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c41a958d-b9f2-484b-b36f-c5f02631935a'), help_text='Unique ID for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
