# Generated by Django 3.2.11 on 2022-01-30 03:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ace3ab70-d22a-4621-87fe-1c246bd7cae4'), help_text='Unique ID for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
