# Generated by Django 3.2.11 on 2022-02-01 09:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6414cdf1-75c1-40f9-ba6c-4c65e1c34e20'), help_text='Unique ID for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
