# Generated by Django 3.2.11 on 2022-02-04 00:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20220201_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f32bfeb5-0def-4d4b-b618-b4df3f202add'), help_text='Unique ID for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
