# Generated by Django 3.2.11 on 2022-02-06 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ea440a1-ec5a-4a6d-a2e9-3cf2a291019b'), help_text='Unique ID for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
